spring:
  application:
    name: walletsystem
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
server:
  port: 8080

coincap:
  api:
    base: https://rest.coincap.io/v3/assets
    key: e3a2bdef59a3ecbc90ff51bee7023bca588e9ed8ad0ee2e2be46e2e0892714d9